### PR TITLE
Adjustments for rails 5, rake fix

### PR DESCRIPTION
**Pull request by tmartin314**
- fix for #22 
- fix for #25 

- Add specs for acts_as_punchable

### CODE REVIEW

**Comment by zedtux** [comment]
Hey @adamcrown, this PR looks good and nice. Would you mind to have a look at it?

**Comment by zedtux** [comment]
@tmartin314 with Rails 5.1 I got the following error when running the migration:

```
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreatePunchesTable < ActiveRecord::Migration[4.2]
/bundle/gems/activerecord-5.1.0/lib/active_record/migration.rb:525:in `inherited'
/application/db/migrate/20170530075334_create_punches_table.rb:1:in `<top (required)>'
...
```

**Comment by zedtux** [comment]
@adamcrown & @tmartin314 I have opened [this PR](https://github.com/tmartin314/punching_bag/pull/1) in order to fix the mentioned issue.

**Comment by tmartin314** [comment]
@zedtux merged, thanks for the fix

**Comment by zedtux** [comment]
Thank you @tmartin314 ! @adamcrown any chance to get this merged and a new release of the gem?

**Comment by zedtux** [comment]
Anyone can you please merge this PR and release a new version of the gem?

**Comment by adamcrown** [comment]
@tmartin314 @zedux my apologies for being so very late in getting to this. I'm merging this now and I should be able to get a new release out soon. Thanks for your patience. I'm no longer using this gem or working for Biola. But I do still want to keep up with my old open source projects.

**Comment by adamcrown** [comment]
Just released version 0.6.0. Thanks guys.

**Comment by zedtux** [comment]
Thank you @adamcrown ! I will update my project as soon as I can :)

**Pull request merged**
